services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Basilicom\AiImageGeneratorBundle\Installer:
    public: true
    arguments:
      $bundle: "@=service('kernel').getBundle('AiImageGeneratorBundle')"

  Basilicom\AiImageGeneratorBundle\Controller\ApiController:
    tags: [ 'controller.service_arguments' ]

  Basilicom\AiImageGeneratorBundle\Config\ConfigurationService: ~
  Basilicom\AiImageGeneratorBundle\Config\ConfigurationFactory: ~

  Basilicom\AiImageGeneratorBundle\Model\RequestFactory: ~

  Basilicom\AiImageGeneratorBundle\Service\RequestService: ~
