ai_image_generator:
  brand:
    colors:
      - "#0062FF"
      - "#B34197"
      - "#FF444A"

  prompt_enhancement:
    service: ~

    services:
#      ollama:
#        baseUrl: ~
#        model: "llama2"

#      basilicom:
#        baseUrl: ~

#      open_ai:
#        baseUrl: "https://api.openai.com/v1"
#        apiKey: "%env(OPEN_AI_API_KEY)%"
#        model: "gpt-3.5-turbo"

  feature_services:
    txt2img: ~
    upscale: ~
    inpaint: ~
    inpaint_background: ~
    image_variations: ~

  services:
    stable_diffusion_api:
      baseUrl: "http://*******/sdapi/v1"
      model: "JuggernautXL"
      inpaint_model: "JuggernautXL"
      steps: 20
      upscaler: "ESRGAN_4x"

    dream_studio:
      baseUrl: "https://api.stability.ai/v1"
      apiKey: "%env(DREAM_STUDIO_API_KEY)%"
      model: "stable-diffusion-xl-1024-v1-0"
      inpaint_model: "stable-diffusion-xl-1024-v1-0"
      steps: 30
      upscaler: "esrgan-v1-x2plus"

    open_ai:
      baseUrl: "https://api.openai.com/v1"
      apiKey: "%env(OPEN_AI_API_KEY)%"

    clip_drop:
      baseUrl: "https://clipdrop-api.co"
      apiKey: "%env(CLIP_DROP_API_KEY)%"
