ai_image_generator:
  feature_services:
    txt2img: stable_diffusion_api
    upscale: stable_diffusion_api
    inpaint_background: stable_diffusion_api
    image_variations: stable_diffusion_api

  services:
    stable_diffusion_api:
      baseUrl: "http://host.docker.internal:7860/sdapi/v1"
      model: "photon_v1"
      inpaint_model: "photon_v1"
      steps: 20
      upscaler: "ESRGAN_4x"

    dream_studio:
      baseUrl: "https://api.stability.ai/v1"
      apiKey: "%env(DREAM_STUDIO_API_KEY)%"
      model: "stable-diffusion-xl-1024-v1-0"
      inpaint_model: "stable-inpainting-512-v2-0"
      steps: 30
      upscaler: "esrgan-v1-x2plus"

    open_ai:
      baseUrl: "https://api.openai.com/v1"
      apiKey: "%env(OPEN_AI_API_KEY)%"

    clip_drop:
      baseUrl: "https://clipdrop-api.co"
      apiKey: "%env(CLIP_DROP_API_KEY)%"
